# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e163bb73775bb123a0c51623d3bc4c918361ee25ee3d07749dcb2cad5fdb0bc9dfef9ad727078a78d700eca641a368322a40c79b7bd61cff6c924fcefb26a1c

test:
  secret_key_base: ad5e1aa16606b90c543d4224d902de64a8824f273f3ea6653604f1eb838a873411cf0f94f04fc34c1bba178a075150990e2a5855b6b04b7221cb9f1f33ece46c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
